// 以下为减少编译代码量而添加的统一处理函数或变量
export const PromiseCls = Promise as typeof Promise<any>,
  undefinedValue = undefined,
  nullValue = null,
  trueValue = true,
  falseValue = false,
  ObjectCls = Object,
  NumberCls = Number,
  StringCls = String,
  BooleanCls = Boolean,
  RegExpCls = RegExp,
  symbolToPrimitive = Symbol.toPrimitive,
  symbolToStringTag = Symbol.toStringTag,
  STR_VALUE_OF = 'valueOf',
  STR_TO_STRING = 'toString',
  DEFAUT_QUEUE_NAME = 'default',
  BEHAVIOR_SILENT = 'silent',
  BEHAVIOR_QUEUE = 'queue',
  BEHAVIOR_STATIC = 'static',
  // 是否为服务端渲染，为了兼容浏览器以及非web客户端环境（如小程序），需要再判断一下process
  isSSR = typeof window === 'undefined' && typeof process !== 'undefined';
